
spring:
  redis:
    host: 192.168.1.11
    port: 6379
  rabbitmq:
    host: 192.168.1.11
    password: 5672
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: blog

mybatis:
  mapper-locations: classpath*:mapper/*.xml

jwt:
  token-key: axilAShsdfjkgikasTDHJC
  aes-key: Axqwn234qt89sdhc

cd:
  blog:
    enable: true
#logging:
#  config: classpath:logback-spring.xml
#  filepath: /log
#  fileSize:
#    max: 100MB
#  fileExpire:

#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.1.11/cd_blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: root
#    password: root
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: cd-blogHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1