server:
  port: 8166

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.1.11

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.11/oauth-center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
